In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from ast import literal_eval
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel,cosine_similarity
from nltk.stem.snowball import SnowballStemmer

In [64]:
df=pd.read_csv("file:///C:/Users/Avinash/Downloads/the-movies-dataset/movies_metadata.csv")

C:\Users\Avinash\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [65]:
print(df.isnull().sum())
print(df.dtypes)
print(df.shape)
df.head(10)

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64
adult                     object
belongs_to_collection     object
budget                    object
genres                    object
homepage                  object
id                        object
imdb_id                   object
original_language         object
original_title            object
overview                  object
popularity                object
poster_path               object
production_companies      object
production_countries      object
release_date              object
revenue                  float64
runtime                  float64
spoken_languages          object
status                    object
tagline                   object
title                     object
video                     object
vote_average             float64
vote_count               float64
dtype: object
(45466, 24)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
5,False,NaN,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,949,tt0113277,en,Heat,"Obsessive master thief, Neil McCauley leads a ...",...,1995-12-15,187436818.0,170.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,A Los Angeles Crime Saga,Heat,False,7.7,1886.0
6,False,NaN,58000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,11860,tt0114319,en,Sabrina,An ugly duckling having undergone a remarkable...,...,1995-12-15,0.0,127.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,You are cordially invited to the most surprisi...,Sabrina,False,6.2,141.0
7,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,45325,tt0112302,en,Tom and Huck,"A mischievous young boy, Tom Sawyer, witnesses...",...,1995-12-22,0.0,97.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The Original Bad Boys.,Tom and Huck,False,5.4,45.0
8,False,NaN,35000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,9091,tt0114576,en,Sudden Death,International action superstar Jean Claude Van...,...,1995-12-22,64350171.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Terror goes into overtime.,Sudden Death,False,5.5,174.0
9,False,"{'id': 645, 'name': 'James Bond Collection', '...",58000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,en,GoldenEye,James Bond must unmask the mysterious head of ...,...,1995-11-16,352194034.0,130.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,No limits. No fears. No substitutes.,GoldenEye,False,6.6,1194.0

In [66]:
def count(x):
    y=x['vote_average']
    y1=x['id']
    words=[]
    for i in range(len(x['vote_average'])):
        if y[i]>=6:
            words.append(y1[i])
        i=i+1
    return words

In [67]:
z=count(df)

In [48]:
df.head(10)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
5,False,NaN,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,949,tt0113277,en,Heat,"Obsessive master thief, Neil McCauley leads a ...",...,1995-12-15,187436818.0,170.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,A Los Angeles Crime Saga,Heat,False,7.7,1886.0
6,False,NaN,58000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,11860,tt0114319,en,Sabrina,An ugly duckling having undergone a remarkable...,...,1995-12-15,0.0,127.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,You are cordially invited to the most surprisi...,Sabrina,False,6.2,141.0
9,False,"{'id': 645, 'name': 'James Bond Collection', '...",58000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,en,GoldenEye,James Bond must unmask the mysterious head of ...,...,1995-11-16,352194034.0,130.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,No limits. No fears. No substitutes.,GoldenEye,False,6.6,1194.0
10,False,NaN,62000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,9087,tt0112346,en,The American President,"Widowed U.S. president Andrew Shepherd, one of...",...,1995-11-17,107879496.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Why can't the most powerful man in the world h...,The American President,False,6.5,199.0
12,False,"{'id': 117693, 'name': 'Balto Collection', 'po...",0,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",NaN,21032,tt0112453,en,Balto,An outcast half-wolf risks his life to prevent...,...,1995-12-22,11348324.0,78.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Part Dog. Part Wolf. All Hero.,Balto,False,7.1,423.0
13,False,NaN,44000000,"[{'id': 36, 'name': 'History'}, {'id': 18, 'na...",NaN,10858,tt0113987,en,Nixon,An all-star cast powers this epic look at Amer...,...,1995-12-22,13681765.0,192.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Triumphant in Victory, Bitter in Defeat. He Ch...",Nixon,False,7.1,72.0

In [68]:
df['genres'] = df['genres'].fillna('[]').apply(literal_eval).apply(lambda x: [i['name'] for i in x] if isinstance(x, list) else [])

In [69]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[Romance, Comedy]",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[Comedy, Drama, Romance]",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,[Comedy],NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [352]:
vote_count=df[df['vote_count'].notnull()]['vote_count'].astype('int')
vote_average=df[df['vote_average'].notnull()]['vote_average'].astype('int')
c=vote_average.mean()
c

6.498106823491501

In [71]:
df['year']=pd.to_datetime(df['release_date'],errors='coerce').apply(lambda x:str(x).split('-')[0] if x!=np.nan else np.nan)

In [72]:
m=vote_count.quantile(0.95)
m

434.0

In [73]:
qualified=df[(df['vote_count']>=m) & (df['vote_count'].notnull()) & (df['vote_average'].notnull())][['year','genres','popularity','vote_count','vote_average','title']]

In [74]:
qualified['vote_count']=qualified['vote_count'].astype('int')
qualified['vote_average']=qualified['vote_average'].astype('int')

In [75]:
s = df.apply(lambda x: pd.Series(x['genres']),axis=1).stack().reset_index(level=1, drop=True)

In [76]:
s.name='genres'
df1=df.drop('genres',axis=1).join(s)

In [77]:
df1

,adult,belongs_to_collection,budget,homepage,id,imdb_id,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,year,genres
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.9469,...,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,1995,Animation
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.9469,...,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,1995,Comedy
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.9469,...,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,1995,Family
1,False,NaN,65000000,NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.0155,...,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,1995,Adventure
1,False,NaN,65000000,NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.0155,...,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,1995,Fantasy
1,False,NaN,65000000,NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.0155,...,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,1995,Family
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,...,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,1995,Romance
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,...,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,1995,Comedy
3,False,NaN,16000000,NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.85949,...,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,1995,Comedy
3,False,NaN,16000000,NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.85949,...,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,1995,Drama
3,False,NaN,16000000,NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.85949,...,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,1995,Romance
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.38752,...,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,1995,Comedy
5,False,NaN,60000000,NaN,949,tt0113277,en,Heat,"Obsessive master thief, Neil McCauley leads a ...",17.9249,...,170.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,A Los Angeles Crime Saga,Heat,False,7.7,1886.0,1995,Action
5,False,NaN,60000000,NaN,949,tt0113277,en,Heat,"Obsessive master thief, Neil McCauley leads a ...",17.9249,...,170.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,A Los Angeles Crime Saga,Heat,False,7.7,1886.0,1995,Crime
5,False,NaN,60000000,NaN,949,tt0113277,en,Heat,"Obsessive master thief, Neil McCauley leads a ...",17.9249,...,170.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,A Los Angeles Crime Saga,Heat,False,7.7,1886.0,1995,Drama
5,False,NaN,60000000,NaN,949,tt0113277,en,Heat,"Obsessive master thief, Neil McCauley leads a ...",17.9249,...,170.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,A Los Angeles Crime Saga,Heat,False,7.7,1886.0,1995,Thriller
6,False,NaN,58000000,NaN,11860,tt0114319,en,Sabrina,An ugly duckling having undergone a remarkable...,6.67728,...,127.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,You are cordially invited to the most surprisi...,Sabrina,False,6.2,141.0,1995,Comedy
6,False,NaN,58000000,NaN,11860,tt0114319,en,Sabrina,An ugly duckling having undergone a remarkable...,6.67728,...,127.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,You are cordially invited to the most surprisi...,Sabrina,False,6.2,141.0,1995,Romance
7,False,NaN,0,NaN,45325,tt0112302,en,Tom and Huck,"A mischievous young boy, Tom Sawyer, witnesses...",2.56116,...,97.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The Original Bad Boys.,Tom and Huck,False,5.4,45.0,1995,Action
7,False,NaN,0,NaN,45325,tt0112302,en,Tom and Huck,"A mischievous young boy, Tom Sawyer, witnesses...",2.56116,...,97.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The Original Bad Boys.,Tom and Huck,False,5.4,45.0,1995,Adventure
7,False,NaN,0,NaN,45325,tt0112302,en,Tom and Huck,"A mischievous young boy, Tom Sawyer, witnesses...",2.56116,...,97.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The Original Bad Boys.,Tom and Huck,False,5.4,45.0,1995,Drama
7,False,NaN,0,NaN,45325,tt0112302,en,Tom and Huck,"A mischievous young boy, Tom Sawyer, witnesses...",2.56116,...,97.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The Original Bad Boys.,Tom and Huck,False,5.4,45.0,1995,Family
8,False,NaN,35000000,NaN,9091,tt0114576,en,Sudden Death,International action superstar Jean Claude Van...,5.23158,...,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Terror goes into overtime.,Sudden Death,False,5.5,174.0,1995,Action
8,False,NaN,35000000,NaN,9091,tt0114576,en,Sudden Death,International action superstar Jean Claude Van...,5.23158,...,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Terror goes into overtime.,Sudden Death,False,5.5,174.0,1995,Adventure
8,False,NaN,35000000,NaN,9091,tt0114576,en,Sudden Death,International action superstar Jean Claude Van...,5.23158,...,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Terror goes into overtime.,Sudden Death,False,5.5,174.0,1995,Thriller
9,False,"{'id': 645, 'name': 'James Bond Collection', '...",58000000,http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,en,GoldenEye,James Bond must unmask the mysterious head of ...,14.686,...,130.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,No limits. No fears. No substitutes.,GoldenEye,False,6.6,1194.0,1995,Adventure
9,False,"{'id': 645, 'name': 'James Bond Collection', '...",58000000,http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,en,GoldenEye,James Bond must unmask the mysterious head of ...,14.686,...,130.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,No limits. No fears. No substitutes.,GoldenEye,False,6.6,1194.0,1995,Action
9,False,"{'id': 645, 'name': 'James Bond Collection', '...",58000000,http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,en,GoldenEye,James Bond must unmask the mysterious head of ...,14.686,...,130.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,No limits. No fears. No substitutes.,GoldenEye,False,6.6,1194.0,1995,Thriller
10,False,NaN,62000000,NaN,9087,tt0112346,en,The American President,"Widowed U.S. president Andrew Shepherd, one of...",6.31844,...,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Why can't the most powerful man in the world h...,The American President,False,6.5,199.0,1995,Comedy
10,False,NaN,62000000,NaN,9087,tt0112346,en,The American President,"Widowed U.S. president Andrew Shepherd, one of...",6.31844,...,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Why can't the most powerful man in the world h...,The American President,False,6.5,199.0,1995,Drama
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45450,False,NaN,0,NaN,49280,tt0135453,fr,L'Homme orchestre,A band-leader has arranged seven chairs for th...,1.109068,...,1.0,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Released,NaN,The One-Man Band,False,6.5,22.0,1900,Fantasy
45450,False,NaN,0,NaN,49280,tt0135453,fr,L'Homme orchestre,A band-leader has arranged seven chairs for th...,1.109068,...,1.0,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Released,NaN,The One-Man Band,False,6.5,22.0,1900,Action
45450,False,NaN,0,NaN,49280,tt0135453,fr,L'Homme orchestre,A band-leader has arranged seven chairs for th...,1.109068,...,1.0,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Released,NaN,The One-Man Band,False,6.5,22.0,1900,Thriller
45451,False,NaN,0,NaN,106807,tt0135571,fr,Nouvelles luttes extravagantes,A series of fantastical wrestling matches.,0.225432,...,2.0,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Released,NaN,The Fat and Lean Wrestling Match,False,6.5,6.0,1900,Comedy
45451,False,NaN,0,NaN,106807,tt0135571,fr,Nouvelles luttes extravagantes,A series of fantastical wrestling matches.,0.225432,...,2.0,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Released,NaN,The Fat and Lean Wrestling Match,False,6.5,6.0,1900,Fantasy
45452,False,NaN,0,NaN,276895,tt3054038,en,Deep Hearts,"Deep Hearts is a film about the Bororo Fulani,...",0.011025,...,58.0,"[{'iso_639_1': 'ff', 'name': 'Fulfulde'}, {'is...",Released,NaN,Deep Hearts,False,0.0,0.0,1981,Documentary
45453,False,NaN,0,NaN,404604,tt5690142,hi,Maa,The bliss of a biology teacher’s family life i...,1.559596,...,146.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Mom,False,6.6,14.0,2017,Crime
45453,False,NaN,0,NaN,404604,tt5690142,hi,Maa,The bliss of a biology teacher’s family life i...,1.559596,...,146.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Mom,False,6.6,14.0,2017,Drama
45453,False,NaN,0,NaN,404604,tt5690142,hi,Maa,The bliss of a biology teacher’s family life i...,1.559596,...,146.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Mom,False,6.6,14.0,2017,Thriller
45454,False,NaN,0,NaN,420346,tt4130180,en,The Morning After,The Morning After is a feature film that consi...,0.139936,...,79.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What happened last night?,The Morning After,False,4.0,2.0,2015,Comedy
45454,False,NaN,0,NaN,420346,tt4130180,en,The Morning After,The Morning After is a feature film that consi...,0.139936,...,79.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What happened last night?,The Morning After,False,4.0,2.0,2015,Drama
45455,False,NaN,0,NaN,67179,tt0069215,it,San Michele aveva un gallo,Sentenced to life imprisonment for illegal act...,0.225051,...,90.0,"[{'iso_639_1': 'it', 'name': 'Italiano'}]",Released,NaN,St. Michael Had a Rooster,False,6.0,3.0,1972,NaN
45456,False,NaN,0,NaN,84419,tt0038621,en,House of Horrors,An unsuccessful sculptor saves a madman named ...,0.222814,...,65.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Meet...The CREEPER!,House of Horrors,False,6.3,8.0,1946,Horror
45456,False,NaN,0,NaN,84419,tt0038621,en,House of Horrors,An unsuccessful sculptor saves a madman named ...,0.222814,...,65.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Meet...The CREEPER!,House of Horrors,False,6.3,8.0,1946,Mystery
45456,False,NaN,0,NaN,84419,tt0038621,en,House of Horrors,An unsuccessful sculptor saves a madman named ...,0.222814,...,65.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Meet...The CREEPER!,House of Horrors,False,6.3,8.0,1946,Thriller
45457,False,NaN,0,NaN,390959,tt0265736,en,Shadow of the Blair Witch,"In this true-crime documentary, we delve into ...",0.076061,...,45.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Shadow of the Blair Witch,False,7.0,2.0,2000,Mystery
45457,False,NaN,0,NaN,390959,tt0265736,en,Shadow of the Blair Witch,"In this true-crime documentary, we delve into ...",0.076061,...,45.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Shadow of the Blair Witch,False,7.0,2.0,2000,Horror
45458,False,NaN,0,NaN,289923,tt0252966,en,The Burkittsville 7,A film archivist revisits the story of Rustin ...,0.38645,...,30.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Do you know what happened 50 years before ""The...",The Burkittsville 7,False,7.0,1.0,2000,Horror
45459,False,NaN,0,NaN,222848,tt0112613,en,Caged Heat 3000,It's the year 3000 AD. The world's most danger...,0.661558,...,85.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Caged Heat 3000,False,3.5,1.0,1995,Science Fiction
45460,False,NaN,0,NaN,30840,tt0102797,en,Robin Hood,"Yet another version of the classic epic, with ...",5.683753,...,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Robin Hood,False,5.7,26.0,1991,Drama
45460,False,NaN,0,NaN,30840,tt0102797,en,Robin Hood,"Yet another version of the classic epic, with ...",5.683753,...,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Robin Hood,False,5.7,26.0,1991,Action
45460,False,NaN,0,NaN,30840,tt0102797,en,Robin Hood,"Yet another version of the classic epic, with ...",5.683753,...,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Robin Hood,False,5.7,26.0,1991,Romance
45461,False,NaN,0,http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,0.072051,...,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0,NaT,Drama
45461,False,NaN,0,http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,0.072051,...,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0,NaT,Family
45462,False,NaN,0,NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,0.178241,...,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0,2011,Drama
45463,False,NaN,0,NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",0.903007,...,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0,2003,Action
45463,False,NaN,0,NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",0.903007,...,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0,2003,Drama
45463,False,NaN,0,NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",0.903007,...,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0,2003,Thriller
45464,False,NaN,0,NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",0.003503,...,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0,1917,NaN
45465,False,NaN,0,NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,0.163015,...,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0,2017,NaN

In [78]:
def recomend(genres,percentile=0.95):
    df2=df1[df1['genres']==genres]
    vote_count=df2[df2['vote_count'].notnull()]['vote_count'].astype('int')
    vote_average=df2[df2['vote_average'].notnull()]['vote_average'].astype('int')
    c=vote_average.mean()
    m=vote_count.quantile(percentile)
    
    qualified=df2[(df2['vote_count']>=m) & (df2['vote_count'].notnull()) & (df2['vote_average'].notnull())][['title','year','popularity','vote_count','vote_average','genres']]
    qualified['vote_count']=qualified['vote_count'].astype('int')
    qualified['vote_average']=qualified['vote_average'].astype('int')
    
    qualified['wr']=qualified.apply(lambda x: (x['vote_count']/(x['vote_count']+m) * x['vote_average'])+(m/(m+x['vote_count'])*c),axis=1)
    #ualified['wr'] = qualified.apply(lambda x: (x['vote_count']/(x['vote_count']+m) * x['vote_average']) + (m/(m+x['vote_count']) * C), axis=1)
    qualified=qualified.sort_values('wr',ascending=False).head(250)
    
    return(qualified)

In [79]:
recomend('Romance').head(15)

,title,year,popularity,vote_count,vote_average,genres,wr
351,Forrest Gump,1994,48.3072,8147,8,Romance,7.869860
10309,Dilwale Dulhania Le Jayenge,1995,34.457,661,9,Romance,7.582757
876,Vertigo,1958,18.2082,1162,8,Romance,7.298862
40251,Your Name.,2016,34.461252,1030,8,Romance,7.235471
883,Some Like It Hot,1959,11.8451,835,8,Romance,7.117619
1132,Cinema Paradiso,1988,14.177,834,8,Romance,7.116921
19901,Paperman,2012,7.19863,734,8,Romance,7.041055
37863,Sing Street,2016,10.672862,669,8,Romance,6.984338
1639,Titanic,1997,26.8891,7770,7,Romance,6.916316
19731,Silver Linings Playbook,2012,14.4881,4840,7,Romance,6.869789
40882,La La Land,2016,19.681686,4745,7,Romance,6.867399
23437,Maleficent,2014,19.4674,4607,7,Romance,6.863766
22168,Her,2013,13.8295,4215,7,Romance,6.852269
20910,The Great Gatsby,2013,17.5989,3885,7,Romance,6.840970
23512,The Fault in Our Stars,2014,16.2747,3868,7,Romance,6.840341

In [80]:
cr=pd.read_csv("file:///C:/Users/Avinash/Downloads/the-movies-dataset/credits.csv")
ky=pd.read_csv("file:///C:/Users/Avinash/Downloads/the-movies-dataset/keywords.csv")

In [21]:
ln=pd.read_csv("file:///C:/Users/Avinash/Downloads/the-movies-dataset/links.csv")
ra=pd.read_csv("file:///C:/Users/Avinash/Downloads/the-movies-dataset/ratings.csv")

In [81]:
cr['id']=cr['id'].astype('int')
ky['id']=ky['id'].astype('int')

In [82]:
df = df.drop([19730, 29503, 35587])

In [83]:
df['id']=df['id'].astype('int')

In [84]:
df=df.merge(cr,on='id')
df=df.merge(ky,on='id')

In [85]:
df.shape

(46628, 28)

In [87]:
df = df[df['id'].isin(z)]

In [88]:
df.shape

(24826, 28)

In [33]:
#df['description']=df['overview']+df['tagline']
#df['description']=df['description'].fillna('')

In [35]:
#tf=TfidfVectorizer(analyzer='word',ngram_range=(1,2),stop_words='english',min_df=0)

In [36]:
#tfidf_matrix=tf.fit_transform(df['description'])

In [37]:
#tfidf_matrix.shape

(46628, 573636)

In [59]:
#cosine=linear_kernel(tfidf_matrix,tfidf_matrix)

In [89]:

df['cast']=df['cast'].apply(literal_eval)
df['crew']=df['crew'].apply(literal_eval)
df['keywords']=df['keywords'].apply(literal_eval)

In [90]:
def get_director(x):
    for i in x:
        if i['job']=='Director':
            return i['name']
        else:
            return np.nan

In [92]:
df['director']=df['crew'].apply(get_director)

In [93]:
df['cast'] = df['cast'].fillna('[]').apply(lambda x: [i['name'] for i in x] if isinstance(x, list) else [])

In [94]:
df['cast']=df['cast'].apply(lambda x: x[:3] if len(x)>=3 else x)

In [95]:
df['keywords'] = df['keywords'].fillna('[]').apply(lambda x: [i['name'] for i in x] if isinstance(x, list) else [])

In [96]:
df['cast']=df['cast'].apply(lambda x:[str.lower(i.replace(" ","")) for i in x])

In [105]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,title,video,vote_average,vote_count,year,cast,crew,keywords,director,director1
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,Toy Story,False,7.7,5415.0,1995,"[tomhanks, timallen, donrickles]","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[jealousy, toy, boy, friendship, friends, riva...",johnlasseter,johnlasseter
1,False,NaN,65000000,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,Jumanji,False,6.9,2413.0,1995,"[robinwilliams, jonathanhyde, kirstendunst]","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[board game, disappearance, based on children'...",nan,nan
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[Romance, Comedy]",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,Grumpier Old Men,False,6.5,92.0,1995,"[waltermatthau, jacklemmon, ann-margret]","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[fishing, best friend, duringcreditsstinger, o...",howarddeutch,howarddeutch
3,False,NaN,16000000,"[Comedy, Drama, Romance]",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,Waiting to Exhale,False,6.1,34.0,1995,"[whitneyhouston, angelabassett, lorettadevine]","[{'credit_id': '52fe44779251416c91011acb', 'de...","[based on novel, interracial relationship, sin...",forestwhitaker,forestwhitaker
5,False,NaN,60000000,"[Action, Crime, Drama, Thriller]",NaN,949,tt0113277,en,Heat,"Obsessive master thief, Neil McCauley leads a ...",...,Heat,False,7.7,1886.0,1995,"[alpacino, robertdeniro, valkilmer]","[{'credit_id': '52fe4292c3a36847f802916d', 'de...","[robbery, detective, bank, obsession, chase, s...",michaelmann,michaelmann

In [104]:
df['director'] = df['director'].astype('str').apply(lambda x: str.lower(x.replace(" ", "")))

In [107]:
s = df.apply(lambda x: pd.Series(x['keywords']),axis=1).stack().reset_index(level=1, drop=True)
s.name = 'keyword'

In [108]:
s=s.value_counts()

In [109]:
s[:5]

woman director      1743
independent film    1035
murder               692
based on novel       541
biography            479
Name: keyword, dtype: int64

In [117]:
j=s[s>10]

In [119]:
stemmer=SnowballStemmer('english')

In [120]:
def filter_keywords(x):
    word=[]
    for i in x:
        if i in j:
            word.append(i)
    return word

In [122]:
df

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,video,vote_average,vote_count,year,cast,crew,keywords,director,director1,keywords1
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,False,7.7,5415.0,1995,"[tomhanks, timallen, donrickles]","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[jealousy, toy, boy, friendship, friends, riva...",johnlasseter,johnlasseter,"[jealousy, toy, boy, friendship, friends, riva..."
1,False,NaN,65000000,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,False,6.9,2413.0,1995,"[robinwilliams, jonathanhyde, kirstendunst]","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[board game, disappearance, based on children'...",nan,nan,"[disappearance, based on children's book]"
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[Romance, Comedy]",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,False,6.5,92.0,1995,"[waltermatthau, jacklemmon, ann-margret]","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[fishing, best friend, duringcreditsstinger, o...",howarddeutch,howarddeutch,"[fishing, best friend, duringcreditsstinger]"
3,False,NaN,16000000,"[Comedy, Drama, Romance]",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,False,6.1,34.0,1995,"[whitneyhouston, angelabassett, lorettadevine]","[{'credit_id': '52fe44779251416c91011acb', 'de...","[based on novel, interracial relationship, sin...",forestwhitaker,forestwhitaker,"[based on novel, interracial relationship, sin..."
5,False,NaN,60000000,"[Action, Crime, Drama, Thriller]",NaN,949,tt0113277,en,Heat,"Obsessive master thief, Neil McCauley leads a ...",...,False,7.7,1886.0,1995,"[alpacino, robertdeniro, valkilmer]","[{'credit_id': '52fe4292c3a36847f802916d', 'de...","[robbery, detective, bank, obsession, chase, s...",michaelmann,michaelmann,"[robbery, detective, bank, obsession, chase, s..."
6,False,NaN,58000000,"[Comedy, Romance]",NaN,11860,tt0114319,en,Sabrina,An ugly duckling having undergone a remarkable...,...,False,6.2,141.0,1995,"[harrisonford, juliaormond, gregkinnear]","[{'credit_id': '52fe44959251416c75039da9', 'de...","[paris, brother brother relationship, chauffeu...",sydneypollack,sydneypollack,"[paris, brother brother relationship, chauffeu..."
9,False,"{'id': 645, 'name': 'James Bond Collection', '...",58000000,"[Adventure, Action, Thriller]",http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,en,GoldenEye,James Bond must unmask the mysterious head of ...,...,False,6.6,1194.0,1995,"[piercebrosnan, seanbean, izabellascorupco]","[{'credit_id': '52fe426ec3a36847f801e14b', 'de...","[cuba, falsely accused, secret identity, compu...",martincampbell,martincampbell,"[cuba, falsely accused, secret identity, secre..."
10,False,NaN,62000000,"[Comedy, Drama, Romance]",NaN,9087,tt0112346,en,The American President,"Widowed U.S. president Andrew Shepherd, one of...",...,False,6.5,199.0,1995,"[michaeldouglas, annettebening, michaelj.fox]","[{'credit_id': '52fe44dac3a36847f80adfa3', 'de...","[white house, usa president, new love, widower...",nan,nan,"[white house, usa president, new love, widower]"
12,False,"{'id': 117693, 'name': 'Balto Collection', 'po...",0,"[Family, Animation, Adventure]",NaN,21032,tt0112453,en,Balto,An outcast half-wolf risks his life to prevent...,...,False,7.1,423.0,1995,"[kevinbacon, bobhoskins, bridgetfonda]","[{'credit_id': '593f24b9c3a3680369002371', 'de...","[wolf, dog-sledding race, alaska, dog, goose, ...",nan,nan,"[wolf, alaska, dog]"
13,False,NaN,44000000,"[History, Drama]",NaN,10858,tt0113987,en,Nixon,An all-star cast powers this epic look at Amer...,...,False,7.1,72.0,1995,"[anthonyhopkins, joanallen, powersboothe]","[{'credit_id': '52fe43c59251416c7501d6f3', 'de...","[usa president, presidential election, waterga...",oliverstone,oliverstone,"[usa president, presidential election, biograp..."
15,False,NaN,52000000,"[Drama, Crime]",NaN,524,tt0112641,en,Casino,The life of the gambling paradise – Las Vegas ...,...,False,7.8,1343.0,1995,"[robertdeniro, sharonstone, joepesci]","[{'credit_id': '52fe424dc3a36847f80139cd', 'de...","[poker, drug abuse, 1970s, overdose, illegal p...",martinscorsese,martinscorsese,"[poker, drug abuse, 1970s, overdose, illegal p..."
16,False,NaN,16500000,"[Drama, Romance]",NaN,4584,tt0114388,en,Sense and Sensibility,"Rich Mr. Dashwood dies, leaving his second wif...",...,False,7.2,364.0,1995,"[katewinslet, emmathompson, hughgrant]","[{'credit_id': '52fe43cec3a36847f807101f', 'de...","[bowling, based on novel, servant, country lif...",anglee,anglee,"[based on novel, servant, country life, inheri..."
17,False,NaN,4000000,"[Crime, Comedy]",NaN,5,tt0113101,en,Four Rooms,It's Ted the Bellhop's first night on the job....,...,False,6.5,539.0,1995,"[timroth, antoniobanderas, jenniferbeals]","[{'credit_id': '52fe420dc3a36847f800011b', 'de...","[hotel, new year's eve, witch, bet, hotel room...",nan,nan,"[hotel, new year's eve, witch, bet, hotel room..."
18,False,"{'id': 3167, 'name': 'Ace Ventura Collection',...",30000000,"[Crime, Comedy, Adventure]",NaN,9273,tt0112281,en,Ace Ventura: When Nature Calls,"Summoned from an ashram in Tibet, Ace finds hi...",...,False,6.1,1128.0,1995,"[jimcarrey, ianmcneice, simoncallow]","[{'credit_id': '52fe44dfc3a36847f80af28b', 'de...","[africa, indigenous, human animal relationship...",steveoedekerk,steveoedekerk,"[africa, human animal relationship]"
20,False,"{'id': 91698, 'name': 'Chili Palmer Collection...",30250000,"[Comedy, Thriller, Crime]",NaN,8012,tt0113161,en,Get Shorty,Chili Palmer is a Miami mobster who gets sent ...,...,False,6.4,305.0,1995,"[johntravolta, genehackman, renerusso]","[{'credit_id': '52fe448dc3a36847f809c729', 'de...","[gambling, miami, based on novel, job, murder,...",barrysonnenfeld,barrysonnenfeld,"[gambling, miami, based on novel, job, murder,..."
21,False,NaN,0,"[Drama, Thriller]",NaN,1710,tt0112722,en,Copycat,An agoraphobic psychologist and a female detec...,...,False,6.5,199.0,1995,"[sigourneyweaver, hollyhunter, willpatton]","[{'credit_id': '52fe430ec3a36847f803722d', 'de...","[police brutality, psychology, police operatio...",nan,nan,"[police brutality, psychology, police operatio..."
22,False,NaN,50000000,"[Action, Adventure, Crime, Thriller]",NaN,9691,tt0112401,en,Assassins,Assassin Robert Rath arrives at a funeral to k...,...,False,6.0,394.0,1995,"[sylvesterstallone, antoniobanderas, juliannem...","[{'credit_id': '52fe451cc3a36847f80bd145', 'de...","[competition, assassination, cia, bank, cat, m...",richarddonner,richarddonner,"[competition, assassination, cia, bank, cat, m..."
23,False,NaN,0,"[Drama, Fantasy, Science Fiction, Thriller]",NaN,12665,tt0114168,en,Powder,Harassed by classmates who won't accept his sh...,...,False,6.3,143.0,1995,"[marysteenburgen, seanpatrickflanery, lancehen...","[{'credit_id': '52fe45129251416c7504ab67', 'de...","[dead animal, shot to death, teenage boy, held...",victorsalva,victorsalva,"[shot to death, teenage boy]"
24,False,NaN,3600000,"[Drama, Romance]",http://www.mgm.com/title_title.do?title_star=L...,451,tt0113627,en,Leaving Las Vegas,"Ben Sanderson, an alcoholic Hollywood screenwr...",...,False,7.1,365.0,1995,"[nicolascage, elisabethshue, juliansands]","[{'credit_id': '52fe4245c3a36847f80111c3', 'de...","[individual, prostitute, alcohol, casino, love...",nan,nan,"[individual, prostitute, alcohol, casino, love..."
25,False,NaN,0,[Drama],NaN,16420,tt0114057,en,Othello,The evil Iago pretends to be friend of Othello...,...,False,7.0,33.0,1995,"[laurencefishburne, irènejacob, kennethbranagh]","[{'credit_id': '5462510ec3a368082d000121', 'de...","[shakespeare, jealousy, friends, moor]",nan,nan,"[shakespeare, jealousy, friends]"
26,False,NaN,12000000,"[Comedy, Drama, Family]",NaN,9263,tt0114011,en,Now and Then,Waxing nostalgic about the bittersweet passage...,...,False,6.6,91.0,1995,"[christinaricci, rosieo'donnell, thorabirch]","[{'credit_id': '52fe44dec3a36847f80aed45', 'de...","[1970s, female friendship, coming of age, gyne...",leslilinkaglatter,leslilinkaglatter,"[1970s, female friendship, coming of age, woma..."
27,False,NaN,0,"[Drama, Romance]",NaN,17015,tt0114117,en,Persuasion,This film adaptation of Jane Austen's last nov...,...,False,7.4,36.0,1995,"[amandaroot, ciaránhinds, susanfleetwood]","[{'credit_id': '52fe46ff9251416c7508a8b3', 'de...","[captain, napoleonic wars, old flame, admiral]",rogermichell,rogermichell,[captain]
28,False,NaN,18000000,"[Fantasy, Science Fiction, Adventure]",NaN,902,tt0112682,fr,La Cité des Enfants Perdus,A scientist in a surrealist society kidnaps ch...,...,False,7.6,308.0,1995,"[ronperlman, dominiquepinon, judithvittet]","[{'credit_id': '52fe428ac3a36847f8026c6f', 'de...","[clone, dream, island, eye, dystopia, aging, f...",jean-pierrejeunet,jean-pierrejeunet,"[dream, island, dystopia, aging, friendship, r..."
29,False,NaN,0,"[Drama, Crime]",NaN,37557,tt0115012,zh,摇啊摇，摇到外婆桥,A provincial boy related to a Shanghai crime f...,...,False,6.5,17.0,1995,"[gongli, libao-tian, wangxiaoxiao]","[{'credit_id': '52fe46559251416c910511c9', 'de...","[servant, cabaret, shanghai, diva, uncle, mist...",zhangyimou,zhangyimou,"[servant, cabaret, shanghai, uncle, mistress]"
30,False,NaN,0,"[Drama, Crime]",NaN,9909,tt0112792,en,Dangerous Minds,Former Marine Louanne Johnson lands a gig teac...,...,False,6.4,249.0,1995,"[michellepfeiffer, georgedzundza, courtneyb.va...","[{'credit_id': '52fe4546c3a36847f80c4e4b', 'de...","[rap music, karate, high school, naval officer...",nan,nan,"[rap music, high school, teacher, amusement park]"
31,False,NaN,29500000,"[Science Fiction, Thriller, Mystery]",NaN,63,tt0114746,en,Twelve Monkeys,"In the year 2035, convict James Cole reluctant...",...,False,7.4,2470.0,1995,"[brucewillis, madeleinestowe, bradpitt]","[{'credit_id': '52fe4212c3a36847f8001ac7', 'de...","[schizophrenia, philadelphia, cassandra syndro...",terrygilliam,terrygilliam,"[schizophrenia, time travel, post-apocalyptic,..."
32,False,NaN,0,"[Romance, Adventure]",NaN,78802,tt0114952,fr,"Guillaumet, les ailes du courage",NaN,...,False,6.8,4.0,1996,"[craigsheffer, elizabethmcgovern, tomhulce]","[{'credit_id': '52fe49b4c3a368484e13a259', 'de...",[],jean-jacquesannaud,jean-jacquesannaud,[]
33,False,"{'id': 9435, 'name': 'Babe Collection', 'poste...",30000000,"[Fantasy, Drama, Comedy, Family]",NaN,9598,tt0112431,en,Babe,Babe is a little pig who doesn't quite know hi...,...,False,6.0,756.0,1995,"[christinecavanaugh, miriammargolyes, dannymann]","[{'credit_id': '52fe450fc3a36847f80b9ff7', 'de...","[sheep, pig, affection, piglet, heroism, talki...",nan,nan,"[sheep, pig, affection, talking animal]"
34,False,NaN,0,"[History, Drama, Romance]",NaN,47018,tt0112637,en,Carrington,The story of the relationship between painter ...,...,False,6.4,16.0,1995,"[emmathompson, jonathanpryce, stevenwaddington]","[{'credit_id': '58594c1ac3a3682fb807e4cf', 'de...","[england, painter, conscientious objector, ind...",nan,nan,"[england, painter, independent film, soldier]"
35,False,NaN,11000000,[Drama],NaN,687,tt0112818,en,Dead Man Walking,A justice drama based on a true story about a ...,...,False,7.3,350.0,1995,"[susansarandon, seanpenn, robertprosky]","[{'credit_id': '52fe426ac3a36847f801cf35', 'de...","[prison, rape, socially deprived family, penal...",nan,nan,"[prison, rape, socially deprived family, death..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46556,False,NaN,0,[Drama],NaN,273279,tt1563665,fr,La peau de chagrin,"In 19th-century France, a man (Thomas Coumans)...",...,False,7.0,1.0,2010,"[jean-pierremarielle, mylènejampanoï, julienho...","[{'credit_id': '538ae8dac3a3687146000a6b', 'de...",[],alainberliner,alainberliner,[]
46559,False,NaN,0,[],NaN,61385,tt0383020,ru,Настройщик,"The Tuner (Russian: Настройщик, Nastroyshchik)...",...,False,6.9,7.0,2004,"[georgiydeliev, allademidova, renatalitvinova]","[{'credit_id': '52fe464fc3a368484e089d33', 'de...",[woman director],kiramuratova,kiramuratova,[woman director]
46560,False,NaN,1254040,"[Romance, Comedy]",http://lmtr.fi/,468707,tt5742932,fi,Lauri Mäntyvaaran tuuheet ripset,NaN,...,False,8.0,1.0,2017,"[inkahaapamäki, rosahonkonen, tiitusrantala]","[{'credit_id': '597e22f69251415d7801c74a', 'de...","[fantasy, youth, weird]",hannaleenahauru,hannaleenahauru,"[fantasy, youth]"
46561,False,NaN,750000,"[Crime, Comedy]",NaN,280422,tt3805180,ru,Все и сразу,NaN,...,False,6.0,4.0,2014,"[andreymuravyov, yuliyakhlynina, antonshurtsov]","[{'credit_id': '53b7a7b90e0a2676b8006ab6', 'de...","[robbery, mob]",romankarimov,romankarimov,[robbery]
46562,False,NaN,0,"[Mystery, Drama]",NaN,38326,tt1227796,ru,Юрьев День,A mother loses her son during a winter visit t...,...,False,6.5,4.0,2008,"[kseniyarappoport, romanshmakov, yevgeniyakuzn...","[{'credit_id': '582590479251417b23007561', 'de...",[],kirillserebrennikov,kirillserebrennikov,[]
46563,False,NaN,0,"[Drama, History, Mystery]",NaN,240789,tt1197626,ru,Чудо,The film is based on real events that took pla...,...,False,6.3,3.0,2009,"[sergeimakovetsky, konstantinkhabenskiy, мария...","[{'credit_id': '57f06fdfc3a3683c3e007507', 'de...",[],aleksandrproshkin,aleksandrproshkin,[]
46565,False,NaN,0,"[Romance, Drama]",NaN,64197,tt1047845,ru,Puteshestvie s domashnimi zhivotnymi,Plucked from an orphanage as a literal love sl...,...,False,6.0,5.0,2007,"[dmitriydyuzhev, kseniyakutepova, annamikhalkova]","[{'credit_id': '52fe46cdc3a368484e0a475d', 'de...",[woman director],verastorozheva,verastorozheva,[woman director]
46572,False,NaN,0,"[Drama, Crime]",NaN,449131,tt0321264,ru,Aprel,NaN,...,False,6.0,1.0,NaT,"[evgeniystychkin, denisburgazliev, aleksandrak...","[{'credit_id': '58d83051c3a368126f0567fe', 'de...",[],nan,nan,[]
46575,False,NaN,0,"[Romance, Drama]",NaN,70965,tt1735198,en,Кука,A woman and a young girl in different cities a...,...,False,6.3,7.0,2007,"[anastasiyadobrynina, dinakorzun, dmitriydyuzhev]","[{'credit_id': '52fe481cc3a368484e0e9b83', 'de...",[],yaroslavchevazhevskiy,yaroslavchevazhevskiy,[]
46579,False,NaN,0,"[Crime, Comedy, Action, Family]",NaN,461297,tt6212210,en,Cop and a Half: New Recruit,In this family-friendly action reboot of the 1...,...,False,6.0,1.0,2017,"[loudiamondphillips, wallaceshawn, ginaholden]","[{'credit_id': '593ba0c29251410593009be3', 'de...","[sequel, tv movie, buddy cop]",nan,nan,"[sequel, tv movie, buddy cop]"
46580,False,NaN,0,[Drama],NaN,258907,tt0071450,en,Dyketactics,Born in Los Angeles but a New Yorker by choice...,...,False,8.0,1.0,1974,[barbarahammer],"[{'credit_id': '531f61c3c3a3685c3700a18d', 'de...","[experimental film, avant-garde, lgbt, woman d...",barbarahammer,barbarahammer,"[experimental film, avant-garde, lgbt, woman d..."
46582,False,NaN,0,"[Drama, Family, Fantasy]",NaN,18098,tt0181199,en,Arabian Nights,Scheherezade puts herself in danger to save Su...,...,False,6.9,21.0,2000,"[miliavital, dougrayscott, jasonscottlee]","[{'credit_id': '5545faee925141499f00288a', 'de...",[],nan,nan,[]
46583,False,NaN,0,"[Drama, Foreign]",NaN,52103,tt0144020,zh,Xiao Wu,Little pocket thief Wu never got away from the...,...,False,7.2,13.0,1997,"[hongweiwang, haohongjian, baitaozuo]","[{'credit_id': '52fe4819c3a36847f8157c9f', 'de...",[independent film],jiazhangke,jiazhangke,[independent film]
46587,False,NaN,0,"[Fantasy, Comedy, Romance, Drama]",NaN,143117,tt0097062,ru,"Chyornaya Roza - Emblema Pechali, Krasnaya Roz...","The story happens mainly around ""The Old Arbat...",...,False,6.5,4.0,1989,"[tatyanadrubich, aleksandrabdulov, aleksandrzb...","[{'credit_id': '52fe4afd9251416c750f49ad', 'de...",[],sergeysolovyov,sergeysolovyov,[]
46589,False,NaN,0,"[Mystery, Drama, Thriller, Horror]",NaN,365432,tt4285960,en,The Sublet,The Sublet is a suspense driven psychological ...,...,False,6.5,4.0,2015,"[tiannanori, markmatechuk, kristamadison]","[{'credit_id': '562e344bc3a3681b5c00ab29', 'de...",[],johnainslie,johnainslie,[]
46595,False,NaN,0,"[Music, Comedy, Family]",NaN,5589,tt0232750,cs,Šíleně smutná princezna,No overview found.,...,False,6.1,4.0,1968,"[helenavondráčková, václavneckář, jaroslavmarvan]","[{'credit_id': '52fe440fc3a36847f807ffa3', 'de...","[fairy tale, wedding, aristocrat, pohádka]",nan,nan,"[fairy tale, wedding, aristocrat]"
46599,False,NaN,0,"[Family, Animation, Romance, Comedy]",NaN,455661,tt6969946,en,In a Heartbeat,A closeted boy runs the risk of being outed by...,...,False,8.3,146.0,2017,[],"[{'credit_id': '5981a15c92514151e0011b51', 'de...","[love, teenager, lgbt, short]",nan,nan,"[love, teenager, lgbt, short]"
46600,False,NaN,0,[Drama],NaN,327237,tt3814486,nl,"Bloed, Zweet en Tranen","Bloed, Zweet en Tranen (Blood, Sweat and Tears...",...,False,6.8,11.0,2015,"[martijnfischer, hadewychminis, fedjavanhuêt]","[{'credit_id': '54edb0e0c3a3686d58003a13', 'de...","[biography, singer]",diederickkoopal,diederickkoopal,"[biography, singer]"
46605,False,NaN,0,"[Comedy, Fantasy, Science Fiction]",NaN,49279,tt0000359,fr,L'Homme à la tête de caoutchouc,A chemist in his laboratory places upon a tabl...,...,False,7.6,29.0,1901,[georgesméliès],"[{'credit_id': '52fe478dc3a36847f813bd5f', 'de...","[laboratory, mad scientist, disembodied head, ...",georgesméliès,georgesméliès,"[laboratory, mad scientist, silent film, short]"
46606,False,NaN,0,[Fantasy],NaN,44333,tt0135179,fr,Les cartes vivantes,A bearded magician holds up a large playing ca...,...,False,6.1,8.0,1905,[georgesméliès],"[{'credit_id': '52fe4684c3a36847f810350b', 'de...","[magic, silent film, trick film]",georgesméliès,georgesméliès,"[magic, silent film]"
46608,False,NaN,0,"[Fantasy, Comedy]",NaN,49271,tt0127948,en,Le locataire diabolique,A man rents an apartment and furnishes it in r...,...,False,6.7,12.0,1909,"[andréméliès, georgesméliès]","[{'credit_id': '52fe478dc3a36847f813bd19', 'de...","[tenant, silent film]",georgesméliès,georgesméliès,[silent film]
46609,False,NaN,0,[],NaN,44324,tt0135631,fr,Le Roi du maquillage,The background of this picture represents a sc...,...,False,6.0,6.0,1904,[georgesméliès],"[{'credit_id': '52fe4684c3a36847f810345f', 'de...",[],georgesméliès,georgesméliès,[]
46612,False,NaN,0,"[Fantasy, Action, Thriller]",NaN,49280,tt0135453,fr,L'Homme orchestre,A band-leader has arranged seven chairs for th...,...,False,6.5,22.0,1900,[georgesméliès],"[{'credit_id': '52fe478dc3a36847f813bd6b', 'de...",[],georgesméliès,georgesméliès,[]
46613,False,NaN,0,"[Comedy, Fantasy]",NaN,106807,tt0135571,fr,Nouvelles luttes extravagantes,A series of fantastical wrestling matches.,...,False,6.5,6.0,1900,"[jeanned'alcy, georgesméliès]","[{'credit_id': '52fe4a71c3a36847f81ce35b', 'de...","[wrestling, sport, silent film, short, fat man]",georgesméliès,georgesméliès,"[wrestling, sport, silent film, short]"
46615,False,NaN,0,"[Crime, Drama, Thriller]",NaN,404604,tt5690142,hi,Maa,The bliss of a biology teacher’s family life i...,...,False,6.6,14.0,2017,"[sridevikapoor, sajalali, akshayekhanna]","[{'credit_id': '58ee55bbc3a3683df500bd0f', 'de...","[physical abuse, sexual assault]",nan,nan,[]
46617,False,NaN,0,[],NaN,67179,tt0069215,it,San Michele aveva un gallo,Sentenced to life imprisonment for illegal act...,...,False,6.0,3.0,1972,"[giuliobrogi, renatocestiè, vitocipolla]","[{'credit_id': '5330178a9251413a720055e3', 'de...",[],nan,nan,[]
46618,False,NaN,0,"[Horror, Mystery, Thriller]",NaN,84419,tt0038621,en,House of Horrors,An unsuccessful sculptor saves a madman named ...,...,False,6.3,8.0,1946,"[rondohatton, robertlowery, virginiagrey]","[{'credit_id': '58152c139251415a7f0047e2', 'de...","[revenge, murder, serial killer, new york city...",nan,nan,"[revenge, murder, serial killer, new york city]"

In [123]:
df['keywords']=df['keywords'].apply(filter_keywords)

In [125]:
df['keywords']=df['keywords'].apply(lambda x:[stemmer.stem(i) for i in x])

In [126]:
df['keywords'] = df['keywords'].apply(lambda x: [str.lower(i.replace(" ", "")) for i in x])

In [127]:
df

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,video,vote_average,vote_count,year,cast,crew,keywords,director,director1,keywords1
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,False,7.7,5415.0,1995,"[tomhanks, timallen, donrickles]","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[jealousi, toy, boy, friendship, friend, rivalri]",johnlasseter,johnlasseter,"[jealousy, toy, boy, friendship, friends, riva..."
1,False,NaN,65000000,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,False,6.9,2413.0,1995,"[robinwilliams, jonathanhyde, kirstendunst]","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[disappear, basedonchildren'sbook]",nan,nan,"[disappearance, based on children's book]"
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[Romance, Comedy]",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,False,6.5,92.0,1995,"[waltermatthau, jacklemmon, ann-margret]","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[fish, bestfriend, duringcreditssting]",howarddeutch,howarddeutch,"[fishing, best friend, duringcreditsstinger]"
3,False,NaN,16000000,"[Comedy, Drama, Romance]",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,False,6.1,34.0,1995,"[whitneyhouston, angelabassett, lorettadevine]","[{'credit_id': '52fe44779251416c91011acb', 'de...","[basedonnovel, interracialrelationship, single...",forestwhitaker,forestwhitaker,"[based on novel, interracial relationship, sin..."
5,False,NaN,60000000,"[Action, Crime, Drama, Thriller]",NaN,949,tt0113277,en,Heat,"Obsessive master thief, Neil McCauley leads a ...",...,False,7.7,1886.0,1995,"[alpacino, robertdeniro, valkilmer]","[{'credit_id': '52fe4292c3a36847f802916d', 'de...","[robberi, detect, bank, obsess, chase, shoot, ...",michaelmann,michaelmann,"[robbery, detective, bank, obsession, chase, s..."
6,False,NaN,58000000,"[Comedy, Romance]",NaN,11860,tt0114319,en,Sabrina,An ugly duckling having undergone a remarkable...,...,False,6.2,141.0,1995,"[harrisonford, juliaormond, gregkinnear]","[{'credit_id': '52fe44959251416c75039da9', 'de...","[pari, brotherbrotherrelationship, chauffeur, ...",sydneypollack,sydneypollack,"[paris, brother brother relationship, chauffeu..."
9,False,"{'id': 645, 'name': 'James Bond Collection', '...",58000000,"[Adventure, Action, Thriller]",http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,en,GoldenEye,James Bond must unmask the mysterious head of ...,...,False,6.6,1194.0,1995,"[piercebrosnan, seanbean, izabellascorupco]","[{'credit_id': '52fe426ec3a36847f801e14b', 'de...","[cuba, falselyaccus, secretident, secretintell...",martincampbell,martincampbell,"[cuba, falsely accused, secret identity, secre..."
10,False,NaN,62000000,"[Comedy, Drama, Romance]",NaN,9087,tt0112346,en,The American President,"Widowed U.S. president Andrew Shepherd, one of...",...,False,6.5,199.0,1995,"[michaeldouglas, annettebening, michaelj.fox]","[{'credit_id': '52fe44dac3a36847f80adfa3', 'de...","[whitehous, usapresid, newlov, widow]",nan,nan,"[white house, usa president, new love, widower]"
12,False,"{'id': 117693, 'name': 'Balto Collection', 'po...",0,"[Family, Animation, Adventure]",NaN,21032,tt0112453,en,Balto,An outcast half-wolf risks his life to prevent...,...,False,7.1,423.0,1995,"[kevinbacon, bobhoskins, bridgetfonda]","[{'credit_id': '593f24b9c3a3680369002371', 'de...","[wolf, alaska, dog]",nan,nan,"[wolf, alaska, dog]"
13,False,NaN,44000000,"[History, Drama]",NaN,10858,tt0113987,en,Nixon,An all-star cast powers this epic look at Amer...,...,False,7.1,72.0,1995,"[anthonyhopkins, joanallen, powersboothe]","[{'credit_id': '52fe43c59251416c7501d6f3', 'de...","[usapresid, presidentialelect, biographi, gove...",oliverstone,oliverstone,"[usa president, presidential election, biograp..."
15,False,NaN,52000000,"[Drama, Crime]",NaN,524,tt0112641,en,Casino,The life of the gambling paradise – Las Vegas ...,...,False,7.8,1343.0,1995,"[robertdeniro, sharonstone, joepesci]","[{'credit_id': '52fe424dc3a36847f80139cd', 'de...","[poker, drugabus, 1970s, overdos, illegalprost...",martinscorsese,martinscorsese,"[poker, drug abuse, 1970s, overdose, illegal p..."
16,False,NaN,16500000,"[Drama, Romance]",NaN,4584,tt0114388,en,Sense and Sensibility,"Rich Mr. Dashwood dies, leaving his second wif...",...,False,7.2,364.0,1995,"[katewinslet, emmathompson, hughgrant]","[{'credit_id': '52fe43cec3a36847f807101f', 'de...","[basedonnovel, servant, countrylif, inherit, m...",anglee,anglee,"[based on novel, servant, country life, inheri..."
17,False,NaN,4000000,"[Crime, Comedy]",NaN,5,tt0113101,en,Four Rooms,It's Ted the Bellhop's first night on the job....,...,False,6.5,539.0,1995,"[timroth, antoniobanderas, jenniferbeals]","[{'credit_id': '52fe420dc3a36847f800011b', 'de...","[hotel, newyear'sev, witch, bet, hotelroom, lo...",nan,nan,"[hotel, new year's eve, witch, bet, hotel room..."
18,False,"{'id': 3167, 'name': 'Ace Ventura Collection',...",30000000,"[Crime, Comedy, Adventure]",NaN,9273,tt0112281,en,Ace Ventura: When Nature Calls,"Summoned from an ashram in Tibet, Ace finds hi...",...,False,6.1,1128.0,1995,"[jimcarrey, ianmcneice, simoncallow]","[{'credit_id': '52fe44dfc3a36847f80af28b', 'de...","[africa, humananimalrelationship]",steveoedekerk,steveoedekerk,"[africa, human animal relationship]"
20,False,"{'id': 91698, 'name': 'Chili Palmer Collection...",30250000,"[Comedy, Thriller, Crime]",NaN,8012,tt0113161,en,Get Shorty,Chili Palmer is a Miami mobster who gets sent ...,...,False,6.4,305.0,1995,"[johntravolta, genehackman, renerusso]","[{'credit_id': '52fe448dc3a36847f809c729', 'de...","[gambl, miami, basedonnovel, job, murder, trav...",barrysonnenfeld,barrysonnenfeld,"[gambling, miami, based on novel, job, murder,..."
21,False,NaN,0,"[Drama, Thriller]",NaN,1710,tt0112722,en,Copycat,An agoraphobic psychologist and a female detec...,...,False,6.5,199.0,1995,"[sigourneyweaver, hollyhunter, willpatton]","[{'credit_id': '52fe430ec3a36847f803722d', 'de...","[policebrut, psycholog, policeoper, serialkil,...",nan,nan,"[police brutality, psychology, police operatio..."
22,False,NaN,50000000,"[Action, Adventure, Crime, Thriller]",NaN,9691,tt0112401,en,Assassins,Assassin Robert Rath arrives at a funeral to k...,...,False,6.0,394.0,1995,"[sylvesterstallone, antoniobanderas, juliannem...","[{'credit_id': '52fe451cc3a36847f80bd145', 'de...","[competit, assassin, cia, bank, cat, mexicanst...",richarddonner,richarddonner,"[competition, assassination, cia, bank, cat, m..."
23,False,NaN,0,"[Drama, Fantasy, Science Fiction, Thriller]",NaN,12665,tt0114168,en,Powder,Harassed by classmates who won't accept his sh...,...,False,6.3,143.0,1995,"[marysteenburgen, seanpatrickflanery, lancehen...","[{'credit_id': '52fe45129251416c7504ab67', 'de...","[shottodeath, teenageboy]",victorsalva,victorsalva,"[shot to death, teenage boy]"
24,False,NaN,3600000,"[Drama, Romance]",http://www.mgm.com/title_title.do?title_star=L...,451,tt0113627,en,Leaving Las Vegas,"Ben Sanderson, an alcoholic Hollywood screenwr...",...,False,7.1,365.0,1995,"[nicolascage, elisabethshue, juliansands]","[{'credit_id': '52fe4245c3a36847f80111c3', 'de...","[individu, prostitut, alcohol, casino, loveatf...",nan,nan,"[individual, prostitute, alcohol, casino, love..."
25,False,NaN,0,[Drama],NaN,16420,tt0114057,en,Othello,The evil Iago pretends to be friend of Othello...,...,False,7.0,33.0,1995,"[laurencefishburne, irènejacob, kennethbranagh]","[{'credit_id': '5462510ec3a368082d000121', 'de...","[shakespear, jealousi, friend]",nan,nan,"[shakespeare, jealousy, friends]"
26,False,NaN,12000000,"[Comedy, Drama, Family]",NaN,9263,tt0114011,en,Now and Then,Waxing nostalgic about the bittersweet passage...,...,False,6.6,91.0,1995,"[christinaricci, rosieo'donnell, thorabirch]","[{'credit_id': '52fe44dec3a36847f80aed45', 'de...","[1970s, femalefriendship, comingofag, womandir...",leslilinkaglatter,leslilinkaglatter,"[1970s, female friendship, coming of age, woma..."
27,False,NaN,0,"[Drama, Romance]",NaN,17015,tt0114117,en,Persuasion,This film adaptation of Jane Austen's last nov...,...,False,7.4,36.0,1995,"[amandaroot, ciaránhinds, susanfleetwood]","[{'credit_id': '52fe46ff9251416c7508a8b3', 'de...",[captain],rogermichell,rogermichell,[captain]
28,False,NaN,18000000,"[Fantasy, Science Fiction, Adventure]",NaN,902,tt0112682,fr,La Cité des Enfants Perdus,A scientist in a surrealist society kidnaps ch...,...,False,7.6,308.0,1995,"[ronperlman, dominiquepinon, judithvittet]","[{'credit_id': '52fe428ac3a36847f8026c6f', 'de...","[dream, island, dystopia, age, friendship, res...",jean-pierrejeunet,jean-pierrejeunet,"[dream, island, dystopia, aging, friendship, r..."
29,False,NaN,0,"[Drama, Crime]",NaN,37557,tt0115012,zh,摇啊摇，摇到外婆桥,A provincial boy related to a Shanghai crime f...,...,False,6.5,17.0,1995,"[gongli, libao-tian, wangxiaoxiao]","[{'credit_id': '52fe46559251416c910511c9', 'de...","[servant, cabaret, shanghai, uncl, mistress]",zhangyimou,zhangyimou,"[servant, cabaret, shanghai, uncle, mistress]"
30,False,NaN,0,"[Drama, Crime]",NaN,9909,tt0112792,en,Dangerous Minds,Former Marine Louanne Johnson lands a gig teac...,...,False,6.4,249.0,1995,"[michellepfeiffer, georgedzundza, courtneyb.va...","[{'credit_id': '52fe4546c3a36847f80c4e4b', 'de...","[rapmus, highschool, teacher, amusementpark]",nan,nan,"[rap music, high school, teacher, amusement park]"
31,False,NaN,29500000,"[Science Fiction, Thriller, Mystery]",NaN,63,tt0114746,en,Twelve Monkeys,"In the year 2035, convict James Cole reluctant...",...,False,7.4,2470.0,1995,"[brucewillis, madeleinestowe, bradpitt]","[{'credit_id': '52fe4212c3a36847f8001ac7', 'de...","[schizophrenia, timetravel, post-apocalypt, dy...",terrygilliam,terrygilliam,"[schizophrenia, time travel, post-apocalyptic,..."
32,False,NaN,0,"[Romance, Adventure]",NaN,78802,tt0114952,fr,"Guillaumet, les ailes du courage",NaN,...,False,6.8,4.0,1996,"[craigsheffer, elizabethmcgovern, tomhulce]","[{'credit_id': '52fe49b4c3a368484e13a259', 'de...",[],jean-jacquesannaud,jean-jacquesannaud,[]
33,False,"{'id': 9435, 'name': 'Babe Collection', 'poste...",30000000,"[Fantasy, Drama, Comedy, Family]",NaN,9598,tt0112431,en,Babe,Babe is a little pig who doesn't quite know hi...,...,False,6.0,756.0,1995,"[christinecavanaugh, miriammargolyes, dannymann]","[{'credit_id': '52fe450fc3a36847f80b9ff7', 'de...","[sheep, pig, affect, talkinganim]",nan,nan,"[sheep, pig, affection, talking animal]"
34,False,NaN,0,"[History, Drama, Romance]",NaN,47018,tt0112637,en,Carrington,The story of the relationship between painter ...,...,False,6.4,16.0,1995,"[emmathompson, jonathanpryce, stevenwaddington]","[{'credit_id': '58594c1ac3a3682fb807e4cf', 'de...","[england, painter, independentfilm, soldier]",nan,nan,"[england, painter, independent film, soldier]"
35,False,NaN,11000000,[Drama],NaN,687,tt0112818,en,Dead Man Walking,A justice drama based on a true story about a ...,...,False,7.3,350.0,1995,"[susansarandon, seanpenn, robertprosky]","[{'credit_id': '52fe426ac3a36847f801cf35', 'de...","[prison, rape, sociallydeprivedfamili, deathpe...",nan,nan,"[prison, rape, socially deprived family, death..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46556,False,NaN,0,[Drama],NaN,273279,tt1563665,fr,La peau de chagrin,"In 19th-century France, a man (Thomas Coumans)...",...,False,7.0,1.0,2010,"[jean-pierremarielle, mylènejampanoï, julienho...","[{'credit_id': '538ae8dac3a3687146000a6b', 'de...",[],alainberliner,alainberliner,[]
46559,False,NaN,0,[],NaN,61385,tt0383020,ru,Настройщик,"The Tuner (Russian: Настройщик, Nastroyshchik)...",...,False,6.9,7.0,2004,"[georgiydeliev, allademidova, renatalitvinova]","[{'credit_id': '52fe464fc3a368484e089d33', 'de...",[womandirector],kiramuratova,kiramuratova,[woman director]
46560,False,NaN,1254040,"[Romance, Comedy]",http://lmtr.fi/,468707,tt5742932,fi,Lauri Mäntyvaaran tuuheet ripset,NaN,...,False,8.0,1.0,2017,"[inkahaapamäki, rosahonkonen, tiitusrantala]","[{'credit_id': '597e22f69251415d7801c74a', 'de...","[fantasi, youth]",hannaleenahauru,hannaleenahauru,"[fantasy, youth]"
46561,False,NaN,750000,"[Crime, Comedy]",NaN,280422,tt3805180,ru,Все и сразу,NaN,...,False,6.0,4.0,2014,"[andreymuravyov, yuliyakhlynina, antonshurtsov]","[{'credit_id': '53b7a7b90e0a2676b8006ab6', 'de...",[robberi],romankarimov,romankarimov,[robbery]
46562,False,NaN,0,"[Mystery, Drama]",NaN,38326,tt1227796,ru,Юрьев День,A mother loses her son during a winter visit t...,...,False,6.5,4.0,2008,"[kseniyarappoport, romanshmakov, yevgeniyakuzn...","[{'credit_id': '582590479251417b23007561', 'de...",[],kirillserebrennikov,kirillserebrennikov,[]
46563,False,NaN,0,"[Drama, History, Mystery]",NaN,240789,tt1197626,ru,Чудо,The film is based on real events that took pla...,...,False,6.3,3.0,2009,"[sergeimakovetsky, konstantinkhabenskiy, мария...","[{'credit_id': '57f06fdfc3a3683c3e007507', 'de...",[],aleksandrproshkin,aleksandrproshkin,[]
46565,False,NaN,0,"[Romance, Drama]",NaN,64197,tt1047845,ru,Puteshestvie s domashnimi zhivotnymi,Plucked from an orphanage as a literal love sl...,...,False,6.0,5.0,2007,"[dmitriydyuzhev, kseniyakutepova, annamikhalkova]","[{'credit_id': '52fe46cdc3a368484e0a475d', 'de...",[womandirector],verastorozheva,verastorozheva,[woman director]
46572,False,NaN,0,"[Drama, Crime]",NaN,449131,tt0321264,ru,Aprel,NaN,...,False,6.0,1.0,NaT,"[evgeniystychkin, denisburgazliev, aleksandrak...","[{'credit_id': '58d83051c3a368126f0567fe', 'de...",[],nan,nan,[]
46575,False,NaN,0,"[Romance, Drama]",NaN,70965,tt1735198,en,Кука,A woman and a young girl in different cities a...,...,False,6.3,7.0,2007,"[anastasiyadobrynina, dinakorzun, dmitriydyuzhev]","[{'credit_id': '52fe481cc3a368484e0e9b83', 'de...",[],yaroslavchevazhevskiy,yaroslavchevazhevskiy,[]
46579,False,NaN,0,"[Crime, Comedy, Action, Family]",NaN,461297,tt6212210,en,Cop and a Half: New Recruit,In this family-friendly action reboot of the 1...,...,False,6.0,1.0,2017,"[loudiamondphillips, wallaceshawn, ginaholden]","[{'credit_id': '593ba0c29251410593009be3', 'de...","[sequel, tvmovi, buddycop]",nan,nan,"[sequel, tv movie, buddy cop]"
46580,False,NaN,0,[Drama],NaN,258907,tt0071450,en,Dyketactics,Born in Los Angeles but a New Yorker by choice...,...,False,8.0,1.0,1974,[barbarahammer],"[{'credit_id': '531f61c3c3a3685c3700a18d', 'de...","[experimentalfilm, avant-gard, lgbt, womandire...",barbarahammer,barbarahammer,"[experimental film, avant-garde, lgbt, woman d..."
46582,False,NaN,0,"[Drama, Family, Fantasy]",NaN,18098,tt0181199,en,Arabian Nights,Scheherezade puts herself in danger to save Su...,...,False,6.9,21.0,2000,"[miliavital, dougrayscott, jasonscottlee]","[{'credit_id': '5545faee925141499f00288a', 'de...",[],nan,nan,[]
46583,False,NaN,0,"[Drama, Foreign]",NaN,52103,tt0144020,zh,Xiao Wu,Little pocket thief Wu never got away from the...,...,False,7.2,13.0,1997,"[hongweiwang, haohongjian, baitaozuo]","[{'credit_id': '52fe4819c3a36847f8157c9f', 'de...",[independentfilm],jiazhangke,jiazhangke,[independent film]
46587,False,NaN,0,"[Fantasy, Comedy, Romance, Drama]",NaN,143117,tt0097062,ru,"Chyornaya Roza - Emblema Pechali, Krasnaya Roz...","The story happens mainly around ""The Old Arbat...",...,False,6.5,4.0,1989,"[tatyanadrubich, aleksandrabdulov, aleksandrzb...","[{'credit_id': '52fe4afd9251416c750f49ad', 'de...",[],sergeysolovyov,sergeysolovyov,[]
46589,False,NaN,0,"[Mystery, Drama, Thriller, Horror]",NaN,365432,tt4285960,en,The Sublet,The Sublet is a suspense driven psychological ...,...,False,6.5,4.0,2015,"[tiannanori, markmatechuk, kristamadison]","[{'credit_id': '562e344bc3a3681b5c00ab29', 'de...",[],johnainslie,johnainslie,[]
46595,False,NaN,0,"[Music, Comedy, Family]",NaN,5589,tt0232750,cs,Šíleně smutná princezna,No overview found.,...,False,6.1,4.0,1968,"[helenavondráčková, václavneckář, jaroslavmarvan]","[{'credit_id': '52fe440fc3a36847f807ffa3', 'de...","[fairytal, wed, aristocrat]",nan,nan,"[fairy tale, wedding, aristocrat]"
46599,False,NaN,0,"[Family, Animation, Romance, Comedy]",NaN,455661,tt6969946,en,In a Heartbeat,A closeted boy runs the risk of being outed by...,...,False,8.3,146.0,2017,[],"[{'credit_id': '5981a15c92514151e0011b51', 'de...","[love, teenag, lgbt, short]",nan,nan,"[love, teenager, lgbt, short]"
46600,False,NaN,0,[Drama],NaN,327237,tt3814486,nl,"Bloed, Zweet en Tranen","Bloed, Zweet en Tranen (Blood, Sweat and Tears...",...,False,6.8,11.0,2015,"[martijnfischer, hadewychminis, fedjavanhuêt]","[{'credit_id': '54edb0e0c3a3686d58003a13', 'de...","[biographi, singer]",diederickkoopal,diederickkoopal,"[biography, singer]"
46605,False,NaN,0,"[Comedy, Fantasy, Science Fiction]",NaN,49279,tt0000359,fr,L'Homme à la tête de caoutchouc,A chemist in his laboratory places upon a tabl...,...,False,7.6,29.0,1901,[georgesméliès],"[{'credit_id': '52fe478dc3a36847f813bd5f', 'de...","[laboratori, madscientist, silentfilm, short]",georgesméliès,georgesméliès,"[laboratory, mad scientist, silent film, short]"
46606,False,NaN,0,[Fantasy],NaN,44333,tt0135179,fr,Les cartes vivantes,A bearded magician holds up a large playing ca...,...,False,6.1,8.0,1905,[georgesméliès],"[{'credit_id': '52fe4684c3a36847f810350b', 'de...","[magic, silentfilm]",georgesméliès,georgesméliès,"[magic, silent film]"
46608,False,NaN,0,"[Fantasy, Comedy]",NaN,49271,tt0127948,en,Le locataire diabolique,A man rents an apartment and furnishes it in r...,...,False,6.7,12.0,1909,"[andréméliès, georgesméliès]","[{'credit_id': '52fe478dc3a36847f813bd19', 'de...",[silentfilm],georgesméliès,georgesméliès,[silent film]
46609,False,NaN,0,[],NaN,44324,tt0135631,fr,Le Roi du maquillage,The background of this picture represents a sc...,...,False,6.0,6.0,1904,[georgesméliès],"[{'credit_id': '52fe4684c3a36847f810345f', 'de...",[],georgesméliès,georgesméliès,[]
46612,False,NaN,0,"[Fantasy, Action, Thriller]",NaN,49280,tt0135453,fr,L'Homme orchestre,A band-leader has arranged seven chairs for th...,...,False,6.5,22.0,1900,[georgesméliès],"[{'credit_id': '52fe478dc3a36847f813bd6b', 'de...",[],georgesméliès,georgesméliès,[]
46613,False,NaN,0,"[Comedy, Fantasy]",NaN,106807,tt0135571,fr,Nouvelles luttes extravagantes,A series of fantastical wrestling matches.,...,False,6.5,6.0,1900,"[jeanned'alcy, georgesméliès]","[{'credit_id': '52fe4a71c3a36847f81ce35b', 'de...","[wrestl, sport, silentfilm, short]",georgesméliès,georgesméliès,"[wrestling, sport, silent film, short]"
46615,False,NaN,0,"[Crime, Drama, Thriller]",NaN,404604,tt5690142,hi,Maa,The bliss of a biology teacher’s family life i...,...,False,6.6,14.0,2017,"[sridevikapoor, sajalali, akshayekhanna]","[{'credit_id': '58ee55bbc3a3683df500bd0f', 'de...",[],nan,nan,[]
46617,False,NaN,0,[],NaN,67179,tt0069215,it,San Michele aveva un gallo,Sentenced to life imprisonment for illegal act...,...,False,6.0,3.0,1972,"[giuliobrogi, renatocestiè, vitocipolla]","[{'credit_id': '5330178a9251413a720055e3', 'de...",[],nan,nan,[]
46618,False,NaN,0,"[Horror, Mystery, Thriller]",NaN,84419,tt0038621,en,House of Horrors,An unsuccessful sculptor saves a madman named ...,...,False,6.3,8.0,1946,"[rondohatton, robertlowery, virginiagrey]","[{'credit_id': '58152c139251415a7f0047e2', 'de...","[reveng, murder, serialkil, newyorkc]",nan,nan,"[revenge, murder, serial killer, new york city]"
46619,False,NaN,0,"[Mystery, Horror]",NaN,390959,tt0265736,en,Shadow of the Blair Witch,"In this true-crime documentary, we delve into ...",...,False,7.0,2.0,2000,"[tonyabatemarco, andrebrooks, mariclarecostello]","[{'credit_id': '56ff6ddbc3a3686e9e0013bc', 'de...",[],benrock,benrock,[]

In [128]:
df['keywords']=df['keywords'].astype('str')
df['cast']=df['cast'].astype('str')
df['genres']=df['genres'].astype('str')
df['director']=df['director'].astype('str')

In [129]:
df['soup']=df['keywords']+df['cast']+df['director']+df['genres']

In [131]:
count = CountVectorizer(analyzer='word',ngram_range=(1, 2),min_df=0, stop_words='english')
count_matrix = count.fit_transform(df['soup'])

In [132]:
count_matrix.shape

(24826, 163418)

In [133]:
sim=cosine_similarity(count_matrix,count_matrix)

In [176]:
sim.shape

(24826, 24826)

In [15]:
vectorizer = CountVectorizer() 

corpus = ['This is the first document.','This is the second second document.','And the third one.','Is this the first document?'] 

X = vectorizer.fit_transform(corpus)

In [23]:
X.toarray()

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 2, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]], dtype=int64)

In [21]:
x1=cosine_similarity(X,X)

In [22]:
x1

array([[1.        , 0.63245553, 0.2236068 , 1.        ],
       [0.63245553, 1.        , 0.1767767 , 0.63245553],
       [0.2236068 , 0.1767767 , 1.        , 0.2236068 ],
       [1.        , 0.63245553, 0.2236068 , 1.        ]])

In [6]:
cv

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8',
                input=['hey,how are you', 'i am fine', 'the weather is fine',
                       'this is a testing sentence', 'look at the result'],
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [250]:
df.columns

Index(['level_0', 'index', 'adult', 'belongs_to_collection', 'budget',
       'genres', 'homepage', 'id', 'imdb_id', 'original_language',
       'original_title', 'overview', 'popularity', 'poster_path',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'video', 'vote_average', 'vote_count', 'year', 'cast', 'crew',
       'keywords', 'director', 'director1', 'keywords1', 'soup'],
      dtype='object')

In [287]:
df = df.reset_index()
titles = df['title'].apply(lambda x:str.lower(x))
indices = pd.Series(df.index, index=df['title'].apply(lambda x:str.lower(x)))

In [200]:
titles[6690]

'margaret cho: assassin'

In [337]:
def get_recommendations(title):
    idx = indices[title]
    sim_scores = list(enumerate(sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:31]
    movie_indices = [i[0] for i in sim_scores]
    movies1 = df.iloc[movie_indices][['title', 'genres', 'cast', 'year', 'director','popularity']]
    return movies1.head(20)

In [349]:
#indices['the infinity']

In [351]:
get_recommendations('finding nemo')

,title,genres,cast,year,director,popularity
11052,Winnie the Pooh,"['Animation', 'Family']","['jimcummings', 'travisoates', 'budluckey']",2011,nan,7.35768
9751,Peter & the Wolf,"['Animation', 'Family', 'Music']",[],2006,nan,1.5
8678,Coraline,"['Animation', 'Family']","['dakotafanning', 'terihatcher', 'jennifersaun...",2009,nan,16.6399
9288,The Fly,['Animation'],[],1980,nan,0.300037
15091,Beyond The Mind's Eye,['Animation'],[],1992,nan,0.016204
17126,Kilplased,['Animation'],[],1974,nan,0.04958
16873,Barbie in A Mermaid Tale 2,"['Animation', 'Family']","['nakiaburrise', 'garychalk']",2012,nan,2.95792
11965,One Man Band,"['Animation', 'Family']",[],2005,nan,4.41071
2552,A Monkey's Tale,"['Adventure', 'Animation', 'Family']",[],1999,nan,0.281748
19305,Sanjay's Super Team,['Animation'],[],2015,nan,4.33573
3866,Piglet's Big Movie,"['Animation', 'Family']","['johnfiedler', 'jimcummings', 'andrestojka']",2003,nan,8.51647
10644,Pooh's Grand Adventure: The Search for Christo...,"['Animation', 'Family']","['jimcummings', 'johnfiedler', 'kensansom']",1997,nan,5.83918
15083,Momo,"['Animation', 'Family']","['ericanecci', 'diegoabatantuono', 'giancarlog...",2001,nan,0.986673
15381,The Littlest Angel,"['Animation', 'Family']","['edkelly', 'ninakircher', 'claritypatton']",2011,nan,0.498207
15418,The Land Before Time IX: Journey to the Big Water,"['Animation', 'Family']","['johningle', 'kennethmars', 'miriamflynn']",2002,nan,3.17156
18295,The Grinch Grinches the Cat in the Hat,"['Animation', 'Family']","['masonadams', 'bobholt', 'frankwelker']",1982,nan,0.123535
22371,The Adventures of Scamper the Penguin,"['Animation', 'Family']","['svetlanastepchenko', 'natalyachenchik', 'rol...",1987,nan,1.165088
5960,An Extremely Goofy Movie,"['Animation', 'Family', 'Comedy']","['billfarmer', 'jasonmarsden', 'paulyshore']",2000,nan,10.3684
11893,The Pirates! In an Adventure with Scientists!,"['Animation', 'Adventure', 'Family', 'Comedy']","['hughgrant', 'brendangleeson', 'jeremypiven']",2012,nan,10.2715
15955,Strange Magic,"['Music', 'Animation', 'Family', 'Fantasy']","['alancumming', 'evanrachelwood', 'elijahkelley']",2015,nan,10.1924